
* PRISMANIA
  Entry for GMC Jam 49 by Mercerenies
  + Metroidvania-style platformer
** STORY
   The land of Prismania, inhabited by prisms, has long stood at the
   precipice of the mirror land. The two dimensions have lived at
   peace, but the denizens of the mirror land suddenly stole all
   reflective equipment from Prismania and retreated to their own
   dimension. The Prismanian government fears the worst, so the player
   (Prisman, of course) must travel to the mirror lands and put a stop
   to their evil machinations.
** GAMEPLAY
   The player moves through the map to get to the end.
*** PLAYER ACTIONS
    Those available from the start of the game:
    + [X] Movement (WASD)
    + [X] Jump (WASD)
    + [X] Short range punching attack (left mouse click)
    + [X] +Pick up / throw small objects (right mouse click)+

    Actions available by getting the corresponding upgrade
    + [X] Archery (left mouse click is now a ranged attack; infinite arrows)
    + [X] Bullet time (time slows down when you use archery in air)
    + [X] +Super strength (can pick up and throw larger objects with right mouse as well)+
    + [X] Double jump
    + [X] Wall jumps
    + [ ] Crystal core (allows you to collect portable crystals and use them with RMB)

    Hitting a crystal (with either the punching attack or an arrow)
    causes it to activate or deactivate. An active crystal transports
    a short range around it into the mirror land.

    Note: Cannot use attacks, double jump, or wall jump while carrying
    something. Basically all you can do is drop it, move, and jump
    normally once.
*** FEATURES
    + [X] Player
    + [X] Walls
      - [X] Full walls
      - [X] Regular-world only
      - [X] Mirror world only
    + [-] Generic enemies who walk left/right
      - [X] Exist in both worlds
      - [ ] Variant that's friendly in regular but evil in mirror
      - [ ] Flying variant patrols left and right without gravity
    + [ ] Enemies who fire arrows at you
      - [ ] Exist in both worlds
      - [ ] Variant that's friendly in regular but evil in mirror
      - [ ] Flying variant patrols left and right without gravity
    + [ ] Turrets
      - [ ] Exist in both worlds
      - [ ] Exist only in the regular world
      - [ ] Exist only in the mirror world
      - Note: Turret ammo only exists in the world the turret does (as
        opposed to arrows fired by a Prismanian, which exist in both)
    + [ ] Lasers
      - [ ] Exist in both worlds
      - [ ] Exist only in the regular world
      - [ ] Exist only in the mirror world
      - Like turrets but a continuous beam
    + [X] Stationary crystals
    + [ ] Moving platforms
    + [X] +Small blocks+
      - [X] +Ordinary+
      - [X] +Variant that is a crystal+
    + [X] +Large blocks+
      - [X] +Ordinary+
      - [X] +Variant that is a crystal+
    + [ ] Spring?
    + [ ] Crystal core energy
*** OTHER GOALS
    + [X] Trajectory helper for the arrows
